trigger: none
pr: none

schedules:
- cron: "0 22 * * *"
  displayName: Destroy Development
  branches:
    include:
    - main

stages: 
- stage: clean_up_dev_resources
  jobs:

  - deployment: clean_up_dev_resources

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: DestroyDevResources
            inputs:
              azureSubscription: 'spn-poc-mkdocs-ado-bicep-poc'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $config = (Get-Content bicep/params/poc.json | ConvertFrom-Json)
                $deployment = az deployment sub show --name "mkdocs-$($config.parameters.environment.value)" | ConvertFrom-Json

                foreach ($resourceGroup in $deployment.properties.outputs.resourceGroups.value) {
                  az group delete --name $resourceGroup.name --yes
                }